### ISSUE TITLE
The link in browser_action.html

### ISSUE THREAD

**Issue by 2jun0** [jayhyun-hwang/seeULater#3]
https://github.com/jayhyun-hwang/seeULater/blob/58d430f01da631d1699fcf282162152bf09db135/chromeExtension/browser_action.html#L1

제가 잘 모르는 것일수도 있습니다만, 
이렇게 서버 주소를 github에 올리면 해킹에 악용되거나 서버비에 부담이 있지 않을까요?
config.js 같은  파일을 만들어서 .gitignore에 넣어 숨기는게 나을것 같습니다.

Maybe I'm stupid, but...
Is it okay to reveal the server address on GitHub?
Why don't you make a file like config.js and put it in .gitignore to hide it?

**Comment by 2jun0** [comment]
그리고 혹시 이 프로젝트에 약간 기여해도 될까요?
포트폴리오 용도로 쓰는 거라면 방해가 될까 싶어서요.

And, I'd like to contribute to your project a little bit, can I? 
I am worrying it would be used for portfolio purpose.

**Comment by jayhyun-hwang** [comment]
안녕하세요. 제 프로젝트에 관심 가져 주셔서 감사합니다. 노출된 호스트는 추후 서비스 시 어차피 노출 될 호스트라서 상관 없을 것
같습니다.

보안 상 중요한 정보들은 .gitignore에 추가하여 관리하고 있습니다.

아직 프로젝트가 배포전이라 다른 분의 기여는 신경 못 쓸거 같습니다. 추후에 1차 배포 후에 이슈와 pull request 남겨주시면
감사하겠습니다.

소스는 얼마든지 참고하셔도 좋습니다.

감사합니다. 좋은 하루 되세요~

2021년 11월 13일 (토) 오후 7:26, 2jun0 ***@***.***>님이 작성:

**Comment by jayhyun-hwang** [comment]
안녕하세요. 제 프로젝트에 관심 가져 주셔서 감사합니다. 노출된 호스트는 추후 서비스 시 어차피 노출 될 호스트라서 상관 없을 것 같습니다.

보안 상 중요한 정보들은 .gitignore에 추가하여 관리하고 있습니다. 

아직 프로젝트가 배포전이라 다른 분의 기여는 신경 못 쓸거 같습니다. 추후에 1차 배포 후에 이슈와 pull request 남겨주시면 감사하겠습니다.

소스는 얼마든지 참고하셔도 좋습니다.

감사합니다. 좋은 하루 되세요~

**Comment by 2jun0** [comment]
늦은시간에 답변 감사합니다!
